- name: configure catalogue
  hosts: catalogue
  become: yes

  tasks:
    - name: enable nodejs 20
      ansible.builtin.command: "dnf module enable nodejs:20 -y"

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: create system user roboshop
      ansible.builtin.user:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/nologin
        comment: "RoboShop system User"
    - name: create application directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: download application
      ansible.builtin.get_url:
        url: "https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip"
        dest: /tmp/catalogue.zip
        
    - name: unarchive application
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes
    
    - name: install  dependencies
      community.general.npm:
        path: /app
        state: present
    - name: copy catalogue service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service
    - name: copy mongo repo file
      ansible.builtin.copy:
        src: mongo.repo 
        dest: /etc/yum.repos.d/mongo.repo
    - name: install mongodb client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present
    - name: check products loaded
      ansible.builtin.command: "mongo --host {{ MONGODB_HOST }} --eval 'db.getMongo().getDBNames().indexOf(\"catalogue\")'"
      register: catalogue_output

    - name: Print the output
      ansible.builtin.debug:
        msg: "{{ catalogue_output }}"


  