- name: create ec2 and route 53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-0d6eaeb5fb2bd722b
    ami_id: ami-0220d79f3f480ecf5
    domain_name: devopsskillup.online
    env: dev
    action: create
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ env }}"
      tags:
        Project: roboshop
        Component: "{{ item }}"
        Env: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: ec2_output
    when: action == "create"
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
  - name: create route 53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ env }}.{{ domain_name }}" #mongodb.dev.devopsskillup.online
      type: A
      ttl: 300
      value: "{{ item.instances[0].private_ip_address }}" 
      overwrite: true
    loop: "{{ ec2_output.results }}"
  - name: create route 53 record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "roboshop.{{ env }}.{{ domain_name }}" #roboshop.dev.devopsskillup.online
      type: A
      ttl: 300
      value: "{{ item.instances[0].public_ip_address }}" 
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when: 
    - item.item == "frontend"
    - action == "create"

  - name: delete route 53 record
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ env }}.{{ domain_name }}" #mongodb.dev.devopsskillup.online
      type: A
      ttl: 300
    loop: "{{ instances }}"
    when: action == "destroy"

  - name: delete ec2 instance
    amazon.aws.ec2_instance:
      state: absent
      name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    when: action == "destroy"

      
      
        


  
  