- name: configure shipping server
  hosts: shipping_servers
  become: yes
  tasks:
    - name: install maven
      ansible.builtin.dnf:
        name: maven
        state: present

    - name: create system user roboshop
      ansible.builtin.user:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/nologin
        comment: "RoboShop system User"

    - name: delete app directory
      ansible.builtin.file: 
        path: /app
        state: absent

    - name: create application directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: delete shipping zip file
      ansible.builtin.file:
        path: /tmp/shipping.zip
        state: absent

    - name: download shipping application
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v1.zip
        dest: /tmp/shipping.zip

    - name: unarchive application

      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes 

    



